---

# common
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: install git
    apt: name=git state=installed update_cache=yes

# web
- hosts: web
  become: yes
  become_method: sudo

  tasks:

  - name: install nginx, apache, node
    apt: pkg={{ item }} state=present
    with_items:
    - nginx
    - apache2
    - nodejs	  
    - npm

  - name: install express for node.js    
    npm: name=express global=yes

  - name: write our nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

# lb
- hosts: lb
  become: yes
  become_method: sudo  

  tasks:

  - name: install haproxy and socat
    apt: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy 

  - name: deploy haproxy config
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted