---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant

  tasks:
  - name: Creating pub SSH key
    user: name=root generate_ssh_key=yes

  - name: scan keys
    command: ssh-keyscan lb web1 web2 >> .ssh/known_hosts

  - name: install ssh key
    authorized_key: user=vagrant 
                    key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" 
                    state=present
